[package]
name = "roth"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.20"
tree-sitter-c = "0.20"
colored = "2.0"
atty = "0.2"
clap = { version = "4.0", features = ["derive"] }
rustyline = "14.0"
libloading = "0.8"
tempfile = "3.0"
