[package]
name = "roth-test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
colored = "3.0.0"
futures = "0.3.31"
similar = "2.7.0"
tokio = { version = "1.47.1", features = ["full"] }
